# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprador',
            options={'verbose_name_plural': 'Compradores'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
    ]
