# Generated by Django 6.0.6 on 2026-07-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
