# Generated by Django 6.0.6 on 2026-07-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_comprador_contrasenia_comprador_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='calificacion',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='descripcion_perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='reputacion',
            field=models.CharField(default='Buena', max_length=50),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='proyecto.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='proyecto.vendedor')),
            ],
            options={
                'verbose_name_plural': 'Postulaciones',
                'unique_together': {('vendedor', 'producto')},
            },
        ),
    ]
