# Generated by Django 6.0.7 on 2026-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_vendedor_calificacion_vendedor_descripcion_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_entrega',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria')], default='tarjeta_credito', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_completado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_pago',
            field=models.IntegerField(choices=[(100, 'Pago completo (100%)'), (50, 'Pago parcial (50%)')], default=100),
        ),
    ]
