# Generated by Django 6.0.6 on 2026-07-15 00:36

import proyecto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_pedido_codigo_entrega_pedido_entrega_confirmada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=13, unique=True, validators=[proyecto.models.validar_ruc_ecuador]),
        ),
    ]
