# Generated by Django 6.0.6 on 2026-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_proveedor_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='solicitud_vendedor_activa',
            field=models.BooleanField(default=False),
        ),
    ]
