# Generated by Django 6.0.7 on 2026-07-21 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_producto_solicitud_vendedor_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Umbral mínimo de stock para generar alertas de reposición.'),
        ),
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_activo', models.BooleanField(default=False, help_text='Indica si el vendedor tiene un sistema de facturación conectado.')),
                ('tipo_sistema', models.CharField(choices=[('ninguno', 'Ninguno'), ('sri_ecuador', 'SRI Ecuador (Facturación Electrónica)'), ('otro_erp', 'Otro ERP / Sistema Contable'), ('personalizado', 'API Personalizada')], default='ninguno', max_length=30)),
                ('url_api', models.URLField(blank=True, help_text='URL del API del sistema de facturación (futuro).', null=True)),
                ('api_key', models.CharField(blank=True, help_text='Clave de API (futuro).', max_length=255, null=True)),
                ('ultimo_sync', models.DateTimeField(blank=True, help_text='Última sincronización exitosa.', null=True)),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_facturacion', to='proyecto.vendedor')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
            },
        ),
        migrations.CreateModel(
            name='ListaReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviada', 'Enviada')], default='Borrador', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales para el proveedor.', null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_reposicion', to='proyecto.vendedor')),
            ],
            options={
                'verbose_name': 'Lista de Reposición',
                'verbose_name_plural': 'Listas de Reposición',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemReposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_reposicion', to='proyecto.producto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyecto.listareposicion')),
            ],
            options={
                'verbose_name': 'Ítem de Reposición',
                'verbose_name_plural': 'Ítems de Reposición',
                'unique_together': {('lista', 'producto')},
            },
        ),
    ]
