# Generated by Django 6.0.7 on 2026-07-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_producto_stock_minimo_configuracionfacturacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionfacturacion',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='listareposicion',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='comprador',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_facturacion', to='proyecto.comprador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listareposicion',
            name='comprador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listas_reposicion', to='proyecto.comprador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionfacturacion',
            name='sistema_activo',
            field=models.BooleanField(default=False, help_text='Indica si el tendero tiene un sistema de facturación conectado.'),
        ),
        migrations.CreateModel(
            name='InventarioTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, help_text='Stock actual en la tienda del tendero.')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Umbral mínimo de stock para generar alertas.')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_tienda', to='proyecto.comprador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_tienda', to='proyecto.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Tienda',
                'verbose_name_plural': 'Inventarios de Tienda',
                'unique_together': {('comprador', 'producto')},
            },
        ),
    ]
