# Generated by Django 6.0.7 on 2026-07-26 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_remove_configuracionfacturacion_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total de descuento aplicado en este pedido.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado (ej: 5.00 para 5%).', max_digits=5),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario congelado al momento de crear el pedido.', max_digits=10),
        ),
        migrations.CreateModel(
            name='DescuentoVolumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_minima', models.IntegerField(help_text='Cantidad mínima de unidades para aplicar el descuento.')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ej: 5.00 para 5%).', max_digits=5)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción opcional del descuento.', max_length=200, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_volumen', to='proyecto.producto')),
            ],
            options={
                'verbose_name': 'Descuento por Volumen',
                'verbose_name_plural': 'Descuentos por Volumen',
                'ordering': ['cantidad_minima'],
                'unique_together': {('producto', 'cantidad_minima')},
            },
        ),
    ]
