# Generated by Django 6.0.7 on 2026-07-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_pedido_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud de la tienda', null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud de la tienda', null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='referencias_direccion',
            field=models.TextField(blank=True, help_text='Puntos de referencia para llegar', null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='latitud_actual',
            field=models.FloatField(blank=True, help_text='Latitud actual para rastreo en tiempo real', null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='longitud_actual',
            field=models.FloatField(blank=True, help_text='Longitud actual para rastreo en tiempo real', null=True),
        ),
    ]
