# Generated by Django 6.0.7 on 2026-07-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_pedido_descuento_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/compradores/'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/proveedores/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pagina_web',
            field=models.URLField(blank=True, help_text='Página web oficial de la empresa.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='red_facebook',
            field=models.URLField(blank=True, help_text='Link de Facebook.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='red_instagram',
            field=models.URLField(blank=True, help_text='Link de Instagram.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='red_linkedin',
            field=models.URLField(blank=True, help_text='Link de LinkedIn.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='red_twitter',
            field=models.URLField(blank=True, help_text='Link de Twitter / X.', null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='acepta_letras_cambio',
            field=models.BooleanField(default=False, help_text='Indica si el vendedor acepta ofrecer letras de cambio / crédito a compradores.'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/vendedores/'),
        ),
    ]
