# Generated by Django 6.0.7 on 2026-07-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_comprador_foto_perfil_comprador_telefono_and_more'),
        ('proyecto', '0012_comprador_latitud_comprador_longitud_and_more'),
    ]

    operations = [
    ]
